### ISSUE TITLE
Stuck on response code 441

### ISSUE THREAD

**Issue by aelharda** [kyhau/ssllabs-scan#107]
Hi dev,

While scanning a list, i came across the below error, it seems the script can't get passed it to the next website test

Start analyzing testwebsite.com ...
Status: DNS, wait for 30 seconds...
Status: IN_PROGRESS, wait for 30 seconds...
Start analyzing xx.xxx.xxx.xxx:443 ...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...
Response code: 441 - Error on requesting API. Waiting 30 sec until next retry...

Any help would be appreciated.

**Comment by kyhau** [comment]
Hi @aelharda, I have not experienced a 441 before. Had a quick look at [ssllabs-api-docs-v3](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md) - the "Error Reporting" and "Access Rate and Rate Limiting" sections, cannot find 441 as well.

If you re-run the list, did you get the same error on the same server, or different server in your list?

**Comment by aelharda** [comment]
the error code is caused by a website being offline or using the wrong website format (for example IP:Port).

**Comment by kyhau** [comment]
Hi @aelharda,

This enhancement https://github.com/kyhau/ssllabs-scan/issues/108 on the retry approach should cover your case.It's been implemented and merged. See also https://github.com/kyhau/ssllabs-scan/releases/tag/2.0.0

Also added an unit test for your case here:
https://github.com/kyhau/sslla bs-scan/blob/main/ssllabsscan/tests/test_ssllabs_client.py#L71

**Comment by kyhau** [comment]
No further comment. Close ticket.
