### ISSUE TITLE
API v4 for Qualys SSLLabs

### ISSUE THREAD

**Issue by yoyoden** [kyhau/ssllabs-scan#189]
Hello, just curious if you have plans or an ETA for supporting API v4 now that v3 has been deprecated?  Thank you

[https://notifications.qualys.com/api/2023/09/28/introduction-of-api-v4-for-qualys-ssllabs-and-deprecation-of-api-v3](url)

**Comment by kyhau** [comment]
Hi @yoyoden, thanks for raising the issue. 
Yes I do but just have been busy lately.
I'll probably have time to look into v4 in late Feb / early March.

**Comment by yoyoden** [comment]
Great, thank you

**Comment by yoyoden** [comment]
Bumping to defeat the github-actions bot :)

**Comment by kyhau** [comment]
It seems that v3 and v4 do not have much change except v4 now requires to first register with an organisation email address, and then each api call needs to have that registration email in the request header.

**Comment by kyhau** [comment]
Issue resolved. See https://github.com/kyhau/ssllabs-scan/releases/tag/3.0.0
